---
title: "DS1000 Course Syllabus Fall 2023"
author: "Holly Steeves"
format: 
  html: 
    number-sections: true
    toc: true
    theme: 
      light: flatly
      dark: darkly
editor: visual
---

# Course Information

## Class Information

Term: Fall 2023

Location: NSC-1

Lectures: MWF 8:30-9:20 AM

## List of Prerequisites

One or more of Ontario Secondary School MCV4U, MHF4U, MDM4U, [Mathematics 0109A/B,](https://www.westerncalendar.uwo.ca/Courses.cfm?CourseAcadCalendarID=BRESC_028946_1&SelectedCalendar=Live&ArchiveID=) [Mathematics 0110A/B,](https://www.westerncalendar.uwo.ca/Courses.cfm?CourseAcadCalendarID=MAIN_003376_1&SelectedCalendar=Live&ArchiveID=) [Mathematics 1229A/B,](https://www.westerncalendar.uwo.ca/Courses.cfm?CourseAcadCalendarID=MAIN_020938_1&SelectedCalendar=Live&ArchiveID=) or equivalent.

## List of Antirequisites

[Statistical Sciences 1023A/B,](https://www.westerncalendar.uwo.ca/Courses.cfm?CourseAcadCalendarID=MAIN_013831_1&SelectedCalendar=Live&ArchiveID=) the former [Statistical Sciences 1024A/B](https://www.westerncalendar.uwo.ca/Courses.cfm?CourseAcadCalendarID=KINGS_013832_3&SelectedCalendar=Live&ArchiveID=).Instructor Information

+------------+-------------------+------------------+----------+---------------------+---------------+
| Position   | Name              | Email            | Office   | Phone               | Office Hours  |
+============+===================+==================+==========+=====================+===============+
| Instructor | Dr. Holly Steeves | USE OWL MESSAGES | WSC 233  | 519-661-2111 x86426 | T 11:00-12:30 |
|            |                   |                  |          |                     |               |
|            |                   |                  |          |                     | W 10:00-11:30 |
+------------+-------------------+------------------+----------+---------------------+---------------+

::: callout-warning
Students must use OWL messages to contact Dr. Holly Steeves. Emails will not be answered.
:::

You can expect a response to a message to the instructor within **approximately 48 hours** during the work week (during busy times, it may take a little longer). ***Note that messages will not be answered within the 24-hour period before exams or project deadlines***, nor can I guarantee responses over weekends/holidays.

## Personal Teaching Approach

I believe that students learn best in an inclusive, welcoming environment that sparks questions, discussions and respect from all sides. For this reason, a typical class will involve a lecture period discussing and explaining the material, broken up with non-graded check ins (through the use of Mentimeter) to assess student understanding. Examples will be used both as part of the lectures, and part of active learning, where the students get time to practice the problems themselves. In cases where feedback from the assessment is immediate (such as with Mentimeter), the lecture may be tailored to sections that were most misunderstood. I welcome relevant disruptions to this lecture period such as with questions or discussion topics. I encourage participation and discussions throughout the lectures, and the active learning components. Throughout all of these components, I strive to be respectful to all learners and their individual learning needs, and I expect you to do the same.

## Instructor Policies

As mentioned above, I expect respect and inclusivity in our classroom. To promote this, I have several policies that you should follow:

-   Please do not be late. If you must be, please enter quietly and choose a seat closest to the door to limit the disruption
-   Put your phones on silent and refrain from being on them. If you must answer your phone, immediately and quietly leave the room. I understand there are sometimes emergencies, but this should not disrupt other students.
-   Please have Mentimeter links open and ready to go.
-   Treat others as you would like to be treated. When speaking for the first time in a new group, introduce yourself with your name, and pronouns if you feel comfortable. Do not judge others for their work in this class, their questions, or anything they choose to share.
-   When others are speaking, whether it be instructor or student, listen and do not speak over them.
-   Please allow 1 business day for a response via messages. I will not be answering messages in the evenings, weekends, or holidays, but I will get back to you as soon as possible. The same should be expected of your peers.

# Course Syllabus, Schedule, Delivery Mode

## Course Description

Students will learn how to visualize and analyze continuous and categorical data from various domains, using modern data science tools. Concepts of distributions, sampling, estimation, confidence intervals, experimental design, inference, correlation will be introduced in a practical, data-driven way.

## Learning Outcomes

By the end of this course, students will be able to

-   Understand and correctly use foundational vocabulary associated with Statistics and Data Science.

-   Interpret, create and critically evaluate graphical and numerical data summaries.

-   Understand and appreciate probability, chance, randomness, and 'average'.

-   Understand, assess, and critique the conclusions of data analyses.

-   Apply concepts learned in this course to future courses, careers, and everyday life.

## Tentative Schedule

+-----------+----------------+----------------------+---------------------------------------------------------------------+
| Week      | Dates          | Section              | Lab                                                                 |
+===========+================+======================+=====================================================================+
| 1         | Sept 8         | Syllabus/Outline     |                                                                     |
+-----------+----------------+----------------------+---------------------------------------------------------------------+
| 2         | Sept 11 - 15   | 1.1-1.6              | -   Introduction to Python and Google Colab                         |
|           |                |                      |                                                                     |
|           |                |                      | -   Data frames, arrays, types of variables                         |
+-----------+----------------+----------------------+---------------------------------------------------------------------+
| 3         | Sept 18 - 22   | 2.1 - 2.5            | -   Basic python commands and functions                             |
+-----------+----------------+----------------------+---------------------------------------------------------------------+
| 4         | Sept 25 - 27   | 2.5 - 2.8            | -   Import data                                                     |
|           |                |                      |                                                                     |
|           |                |                      | -   Histogram, pie chart, bar plot                                  |
|           |                |                      |                                                                     |
|           |                |                      | -   Five-number summary                                             |
|           |                |                      |                                                                     |
|           |                |                      | -   Boxplots                                                        |
|           |                |                      |                                                                     |
|           |                |                      | -   Calculating standard deviation                                  |
+-----------+----------------+----------------------+---------------------------------------------------------------------+
| 5         | Oct 2 - 6      | 3.1 - 3.8            | -   Generating normal data and plotting the corresponding histogram |
|           |                |                      |                                                                     |
|           |                |                      | -   Calculating normal proportions                                  |
+-----------+----------------+----------------------+---------------------------------------------------------------------+
| 6         | Oct 11 - 13    | 4.1 - 4.6            | -   Scatterplot                                                     |
|           |                |                      |                                                                     |
|           |                |                      | -   Linear correlation (Python function for Pearson's correlation)  |
+-----------+----------------+----------------------+---------------------------------------------------------------------+
| 7         | Oct 16 - 20    | 5.1 - 5.8 (excl 5.3) | -   Review for Midterm                                              |
+-----------+----------------+----------------------+---------------------------------------------------------------------+
| 8         | Oct 23 - 27    | 6.2 - 6.3            | -   Least-squares regression fit                                    |
|           |                |                      | -   Interpretation of result table                                  |
+-----------+----------------+----------------------+---------------------------------------------------------------------+
| 9         | Oct 30 - Nov 3 | READING              | WEEK                                                                |
+-----------+----------------+----------------------+---------------------------------------------------------------------+
| 10        | Nov 6 - 10     | 8.1 - 8.7            | -   From raw data to two-way table                                  |
|           |                |                      |                                                                     |
|           |                | 9.1 - 9.7            | -   Computing conditional and marginal proportions                  |
|           |                |                      |                                                                     |
|           |                |                      | -   Relative risk, odds ratio                                       |
|           |                |                      |                                                                     |
|           |                |                      | -   Mosaic plot                                                     |
+-----------+----------------+----------------------+---------------------------------------------------------------------+
| 11        | Nov 13 - 17    | 12.1, 12.3 - 12.7    | -   Generating samples                                              |
+-----------+----------------+----------------------+---------------------------------------------------------------------+
| 12        | Nov 20 - 24    | 13.1 - 13.6          | -   Venn diagrams                                                   |
+-----------+----------------+----------------------+---------------------------------------------------------------------+
| 13        | Nov 27 - Dec 1 | 15.1 - 15.6          | -   Mean sampling distribution                                      |
+-----------+----------------+----------------------+---------------------------------------------------------------------+
| 14        | Dec 4 - 8      | 16.1 - 16.4          | -   Building normal based CIs                                       |
|           |                |                      |                                                                     |
|           |                |                      | -   Bootstrap samples                                               |
|           |                |                      |                                                                     |
|           |                |                      | -   Bootstrap CIs                                                   |
+-----------+----------------+----------------------+---------------------------------------------------------------------+

# Course Materials

## Textbook

The Basic Practice of Statistics, 9th Ed, 2021, by D. S. Moore; W. I. Notz; M. l. Fligner

Students can order a physical copy through the Book Store's website or purchase an e-book version through the following link:

<https://store.macmillanlearning.com/ca/product/The-Basic-Practice-of-Statistics/p/1319244378>

## OWL

Students are responsible for checking the course OWL site (http://owl.uwo.ca) on a regular basis for course material and updates. This is the primary method by which information will be distributed to all students in the class. If students need assistance with the course OWL site, they can seek support on the OWL Help page. Alternatively, they can contact the Western Technology Services Helpdesk by phone at 519-661-3800 or ext. 83800.

## iClicker

iClicker will be used for in class feedback and non-graded assessments. Click on the tab on the side of your OWL site where you can install iClicker and join the class.

## Mentimeter

This is a website we will use similar to iClicker but fully anonymous. You can use this to ask anonymous questions, answer polls etc.

## Technical Requirements

Python and Google Colab are the main tools for labs. If you need access to a computer for coursework, please contact the instructor as early as possible.

# Methods of Evaluation

The overall course grade will be calculated as listed below:

+--------------------+---------------+-------------------------------------------+
| Component          | Weight        | Deadline                                  |
+====================+===============+===========================================+
| Lab Attendance     | 5%            | NA                                        |
+--------------------+---------------+-------------------------------------------+
| Assignments (4)    | 20%           | Sept 27, Oct 27, Nov 17, Dec 8            |
+--------------------+---------------+-------------------------------------------+
| Midterm (2 hrs)    | 25%           | Oct 25 - to be confirmed by the Registrar |
+--------------------+---------------+-------------------------------------------+
| Final Exam (3 hrs) | 50%           | TBD - scheduled by the Registrar's office |
+--------------------+---------------+-------------------------------------------+

## Assessment Descriptions

-   **Assignments will be available on the course OWL site. However, you will not submit your solutions to OWL. Instead, [assignments must be submitted through Gradescope]{.underline}** ([https://www.gradescope.ca/](#0)) an online collaborative grading system. It is your responsibility to make sure that your assignment is successfully uploaded and legible. Submissions that cannot be read by the grader will receive a grade of zero. Assignment questions must be assigned properly to each page or the submission will not be graded.

-   After receiving the grades from an assignment, **students will have seven days to submit any regrade requests on that assignment, with the exception of the final assignment**. After this seven-day period, regrade requests will NOT be accepted. Regrade requests must be made using the Gradescope tool "Regrade Request".

-   **Assignment submissions are due 11:55 pm (Eastern Time) on the due date**. Assignments that are up to 24 hours late will receive a deduction of 15% on their mark unless late coupons are used. Late assignments up to 48 hours will receive a deduction of 30% on their mark, unless late coupons are used. **No credit will be given for submissions beyond 48 hours of the deadline time unless a valid academic accommodation is obtained.**

-   Each student will have **2 late coupons** worth 24 hours each that they can use at their own discretion for whatever reason (Note: I do not need to know the reason) towards their assignments. You can use them together on one assignment for a 48 hour extension, or on separate assignments for 24 hour extension. **No extensions will be given for any reason beyond the use of the late coupons, therefore I suggest saving them until you absolutely need them.** You do not need to tell me when you will use the coupons, they will automatically come off the first two late days.

-   Solutions to assignments [**will not**]{.underline} be posted; however, TAs will provide comments on incorrect answers using Gradescope, which will allow students to find out the correct solutions. In addition, students can ask the instructor and TAs for more details on solutions via the Regrade Request tool on Gradescope and during office hours.

-   There are 12 **labs**, however you only need to attend 10 to earn 5% of your grade (10\*0.5%). We will use iClicker to track who is in attendance.

-   **Midterm** is tentatively scheduled for Oct 25, 7-9, to be confirmed by the Registrar. This will be closed book. You will be allowed **one single sided, letter sized, handwritten cheat sheet.**

-   **Final Exam** will be booked by the registrar's office, so date and time is to be determined. This will be closed book. You will be allowed **one double sided, handwritten, letter sized cheat sheet. Handwritten means pen to paper, no printing from a computer or any kind.**

# Student Absences

If you are unable to meet a course requirement due to illness or other serious circumstances, please follow the procedures below.

**Assessments worth less than 10% of the overall course grade:**

The assignments have late coupons to account for any extensions needed, for any reason. No extensions will be given beyond this. For quizzes, the lowest mark gets dropped, so no quizzes will be excused. If you miss a quiz for any reason, that quiz will count as your dropped quiz.

**Assessments worth 10% or more of the overall course grade:**

For work totalling 10% or more of the final course grade, you must provide valid medical or supporting documentation to the Academic Counselling Office of your Faculty of Registration as soon as possible. For further information, please consult the University's medical illness policy at

[https://www.uwo.ca/univsec/pdf/academic_policies/appeals/accommodation_medical.pdf](https://www.uwo.ca/univsec/pdf/academic_policies/appeals/accommodation_medical.pdf.).

The Student Medical Certificate is available at

[https://www.uwo.ca/univsec/pdf/academic_policies/appeals/medicalform.pdf](https://www.uwo.ca/univsec/pdf/academic_policies/appeals/medicalform.pdf.).

If the midterm exam is missed, the weight will be shifted towards the final exam.

## Absences from Final Examinations

If you miss the Final Exam, please contact the Academic Counselling office of your Faculty of Registration as soon as you are able to do so.  They will assess your eligibility to write the Special Examination (the name given by the University to a makeup Final Exam).

You may also be eligible to write the Special Exam if you are in a "Multiple Exam Situation" (e.g., more than 2 exams in 23-hour period, more than 3 exams in a 47-hour period).

::: callout-caution
Missed work can *only* be excused through one of the mechanisms above.  Being asked not to attend an in-person course requirement due to potential COVID-19 symptoms is **not** sufficient on its own.
:::

# Accommodation and Accessibility

## **Religious Accommodation**

When a course requirement conflicts with a religious holiday that requires an absence from the University or prohibits certain activities, students should request accommodation for their absence in writing at least two weeks prior to the holiday to the course instructor and/or the Academic Counselling office of their Faculty of Registration.  Please consult University's list of recognized religious holidays (updated annually) at

<https://multiculturalcalendar.com/ecal/index.php?s=c-univwo>.

## **Accommodation Policies**

Students with disabilities are encouraged to contact Accessible Education, which provides recommendations for accommodation based on medical documentation or psychological and cognitive testing. The policy on Academic Accommodation for Students with Disabilities can be found at:

[https://www.uwo.ca/univsec/pdf/academic_policies/appeals/Academic Accommodation_disabilities.pdf](https://www.uwo.ca/univsec/pdf/academic_policies/appeals/Academic%20Accommodation_disabilities.pdf).

# Academic Policies

The website for Registrarial Services is <http://www.registrar.uwo.ca>.

In accordance with policy,

<https://www.uwo.ca/univsec/pdf/policies_procedures/section1/mapp113.pdf>,

the centrally administered e-mail account provided to students will be considered the individual's official university e-mail address.  It is the responsibility of the account holder to ensure that e-mail received from the University at their official university address is attended to in a timely manner.

Participants in this course are not permitted to record lectures and/or labs, except where recording is an approved accommodation, and the participant has the prior written permission of the instructor.

Online services such as Chegg are actively monitored. Any questions that are coming out from assignments and are posted to an online service will be searched. Such an activity will be considered as a scholastic offence and will result in an academic penalty.

A scientific calculator will be allowed on the midterm and final exam. A graphics calculator will not be allowed.

**Scholastic offences** are taken seriously and students are directed to read the appropriate policy, specifically, the definition of what constitutes a Scholastic Offence, at the following Web site:

<http://www.uwo.ca/univsec/pdf/academic_policies/appeals/scholastic_discipline_undergrad.pdf>.

Clickers, specifically Mentimeter will be used in this class for instant feedback and non-graded assessments. Clickers will not be used for any marks towards the course.

# Support Services

Please visit the Science & Basic Medical Sciences Academic Counselling webpage for information on adding/dropping courses, academic considerations for absences, appeals, exam conflicts, and many other academic related matters: <https://www.uwo.ca/sci/counselling/>.

Students who are in emotional/mental distress should refer to Mental Health\@Western (<https://uwo.ca/health/>) for a complete list of options about how to obtain help.

Western is committed to reducing incidents of gender-based and sexual violence and providing compassionate support to anyone who has gone through these traumatic events. If you have experienced sexual or gender-based violence (either recently or in the past), you will find information about support services for survivors, including emergency contacts at

<https://www.uwo.ca/health/student_support/survivor_support/get-help.html>.

To connect with a case manager or set up an appointment, please contact support\@uwo.ca.

Please contact the course instructor if you require lecture or printed material in an alternate format or if any other arrangements can make this course more accessible to you.  You may also wish to contact Accessible Education at

<http://academicsupport.uwo.ca/accessible_education/index.html>

if you have any questions regarding accommodations.

Learning-skills counsellors at the Student Development Centre (<https://learning.uwo.ca>) are ready to help you improve your learning skills. They offer presentations on strategies for improving time management, multiple-choice exam preparation/writing, textbook reading, and more. Individual support is offered throughout the Fall/Winter terms in the drop-in Learning Help Centre, and year-round through individual counselling.

Western University is committed to a thriving campus as we deliver our courses in the mixed model of both virtual and face-to-face formats.  We encourage you to check out the Digital Student Experience website to manage your academics and well-being: <https://www.uwo.ca/se/digital/>.

Additional student-run support services are offered by the USC, <https://westernusc.ca/services/>.
